<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 3.1 (Python 3.7.0 on win32)" generated="20181229 14:06:02.836" rpa="false">
<suite id="s1" name="Tx Test" source="C:\Users\czj\Documents\codes\blockchain\chainbot\tests\tx_test.robot">
<kw name="InitSession" library="vers" type="setup">
<kw name="Create Session" library="RequestsLibrary">
<doc>Create Session: create a HTTP session to a server</doc>
<arguments>
<arg>LOCAL</arg>
<arg>${LOCAL_URL}</arg>
</arguments>
<msg timestamp="20181229 14:06:02.998" level="INFO">Creating Session using : alias=LOCAL, url=http://127.0.0.1:8000, headers={},                     cookies=None, auth=None, timeout=None, proxies=None, verify=False,                     debug=0 </msg>
<status status="PASS" starttime="20181229 14:06:02.998" endtime="20181229 14:06:02.999"></status>
</kw>
<kw name="Create Session" library="RequestsLibrary">
<doc>Create Session: create a HTTP session to a server</doc>
<arguments>
<arg>REMOTE</arg>
<arg>${REMOTE_URL}</arg>
</arguments>
<msg timestamp="20181229 14:06:03.000" level="INFO">Creating Session using : alias=REMOTE, url=http://172.18.92.107:38000, headers={},                     cookies=None, auth=None, timeout=None, proxies=None, verify=False,                     debug=0 </msg>
<status status="PASS" starttime="20181229 14:06:03.000" endtime="20181229 14:06:03.000"></status>
</kw>
<status status="PASS" starttime="20181229 14:06:02.998" endtime="20181229 14:06:03.000"></status>
</kw>
<test id="s1-t1" name="001">
<kw name="Log To Console" library="BuiltIn">
<doc>Logs the given message to the console.</doc>
<arguments>
<arg>发送模拟交易</arg>
</arguments>
<status status="PASS" starttime="20181229 14:06:03.003" endtime="20181229 14:06:03.003"></status>
</kw>
<kw name="${INDEX} IN RANGE [ 0 | ${arg_gentxnum} ]" type="for">
<kw name="${INDEX} = 0" type="foritem">
<kw name="SendAndCheckTx">
<arguments>
<arg>10</arg>
</arguments>
<assign>
<var>${TxhashAndStatus}</var>
</assign>
<kw name="Fetch Info" library="vers">
<doc>发送请求,无Data</doc>
<arguments>
<arg>${TSTSendOneTx}</arg>
<arg>txhash</arg>
</arguments>
<assign>
<var>${txhash}</var>
</assign>
<kw name="Post Data" library="vers">
<doc>发送请求</doc>
<arguments>
<arg>${method}</arg>
<arg>None</arg>
<arg>@{retfields}</arg>
<arg>server=${server}</arg>
</arguments>
<assign>
<var>${resp}</var>
</assign>
<kw name="Log" library="BuiltIn">
<doc>Logs the given message with the given level.</doc>
<arguments>
<arg>postdata=${data}</arg>
</arguments>
<msg timestamp="20181229 14:06:03.005" level="INFO">postdata=None</msg>
<status status="PASS" starttime="20181229 14:06:03.005" endtime="20181229 14:06:03.005"></status>
</kw>
<kw name="Post Request" library="RequestsLibrary">
<doc>Send a POST request on the session object found using the
given `alias`</doc>
<arguments>
<arg>${server}</arg>
<arg>${method}</arg>
<arg>data=${data}</arg>
</arguments>
<assign>
<var>${resp}</var>
</assign>
<msg timestamp="20181229 14:06:04.028" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001832D314F98&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /cks/tst/pblte.do</msg>
<msg timestamp="20181229 14:06:05.235" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001832D2FFEB8&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /cks/tst/pblte.do</msg>
<msg timestamp="20181229 14:06:06.640" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001832BDA5208&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /cks/tst/pblte.do</msg>
<msg timestamp="20181229 14:06:07.702" level="FAIL">ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /cks/tst/pblte.do (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001832BDA5710&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))</msg>
<status status="FAIL" starttime="20181229 14:06:03.005" endtime="20181229 14:06:07.703"></status>
</kw>
<status status="FAIL" starttime="20181229 14:06:03.004" endtime="20181229 14:06:07.703"></status>
</kw>
<status status="FAIL" starttime="20181229 14:06:03.004" endtime="20181229 14:06:07.703"></status>
</kw>
<status status="FAIL" starttime="20181229 14:06:03.004" endtime="20181229 14:06:07.704"></status>
</kw>
<status status="FAIL" starttime="20181229 14:06:03.004" endtime="20181229 14:06:07.704"></status>
</kw>
<status status="FAIL" starttime="20181229 14:06:03.003" endtime="20181229 14:06:07.704"></status>
</kw>
<doc>发送并检查模拟交易:3</doc>
<status status="FAIL" starttime="20181229 14:06:03.001" endtime="20181229 14:06:07.705" critical="yes">ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /cks/tst/pblte.do (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001832BDA5710&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))</status>
</test>
<status status="FAIL" starttime="20181229 14:06:02.838" endtime="20181229 14:06:07.708"></status>
</suite>
<statistics>
<total>
<stat pass="0" fail="1">Critical Tests</stat>
<stat pass="0" fail="1">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" id="s1" name="Tx Test">Tx Test</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20181229 14:06:04.028" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001832D314F98&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /cks/tst/pblte.do</msg>
<msg timestamp="20181229 14:06:05.235" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001832D2FFEB8&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /cks/tst/pblte.do</msg>
<msg timestamp="20181229 14:06:06.640" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001832BDA5208&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /cks/tst/pblte.do</msg>
</errors>
</robot>
